path_languages = "languages"
path_texts = "texts"
default_language = "english_1k.json"
default_text = "lotr.txt"
path_dir_setting = "config"
setting_solo_games_filename = "solo_games_settings.toml"
miliseconds_per_frame = 20
