[game_settings]
keep_seed = false

[game_settings.clock_game_settings]
time = 30

[game_settings.race_game_settings]
number_words = 10

[game_settings.infinite_game_settings]

[game_settings.text_settings]
filename = "lotr.txt"

[game_settings.text_settings.text_origin.Text]
start_end_sentence = "Any"
starting_point = "Beginning"
